using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RatTrap : MonoBehaviour
{
    public Animator trapAnimator;
    private bool trigged;

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player") && !trigged)
        {
            trigged = true;
            other.GetComponent<Health>().RemoveHP(10);
            // Play the snap animation
            trapAnimator.SetTrigger("Snap");

            // Destroy the trap after 1 second
            Destroy(this.gameObject, 2f);
        }
    }
}