using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Collections;
using UnityEngine;
using TMPro;

public class GameOverScreen : MonoBehaviour
{
    public TMP_Text levelReached;

    public void Setup(int score)
    {
        transform.Find("BackGround").gameObject.SetActive(true);
        levelReached.text = score.ToString() + " LEVEL";
    }

    public void RespawnButton() {
        SceneManager.LoadScene("Main_Game");
    }

    public void SaveQuitButton()
    {
        SceneManager.LoadScene("Main_Menu");
    }

}
